checkly/checkly-go-sdk

- checkly_test.go
- types.go
This allow people to access the content of ApiCheckResult and BrowserCheckResult if they want check it. I left it loosely typed since it is just carrying information
> turn api and browser checks results to a map

- checkly.go
- checkly_integration_test.go
- checkly_test.go
- types.go
Resolves #46 
- Replace printf("%v", string(byteSlice)) with printf("%s", byteSlice)
- Use t.Error in test cases instead of t.Fatal (t.Fail was giving an argument syntax error)
- Change function description to avoid redundancy
> Code improvements and remove commented code

- types.go
Resolves #61 
- Add omitempty to the locations field so if it comes empty we can add the default value.
> fix: add omitempty on locations field

- types.go
The create check API endpoint allows a new param, skipSSL for request.
> Resolves #67
> feature: add skipSSL request property [sc-6270]

- README.md
- checkly.go
- checkly_integration_test.go
- checkly_test.go
- demo/main.go
- fixtures/CreateCheck.json
- fixtures/CreateGroup.json
- fixtures/GetCheck.json
- fixtures/UpdateCheck.json
- fixtures/UpdateGroup.json
- types.go
Depreacete `sslCertificates` property from `AlertSettings` and `SSLCertificates` type.
> Resolves https://github.com/checkly/checkly-go-sdk/issues/70
> Resolves https://github.com/checkly/checkly-go-sdk/issues/85
> refactor: deprecate sslCertificates from AlertSettings and sslChecks from Checks

- types.go
Add missing `omitempty` to `Dashboard` and `MaintenanceWindow` types.
> Resolves #75
> chore: add missing `omitempty` to `Dashboard` and `MaintenanecWindow`

- types.go
Add `omitempty` to env var key.
> Resolves #89
> fix: add `omitempty` to env var key

- checkly_test.go
- types.go
* [] New Features
Add missing `webhook_type` field to alert channels.
> feat: add webhook_type field to alert channels

- types.go
Add isPrivate and Keys property to Dashboard type, this allows user to receive the password when creating a private dashboard using go SDK. 
Testing steps:
1) On demo/main.go set isPrivate property to true in "dashboard" variable
2) On demo/main.go add a function that creates the dashboard, for example:
```
dashboard, err := client.CreateDashboard(ctx, dashboard)
if err != nil {
log.Fatalf("creating dashboard: %v", err)
}
fmt.Printf("New private dashboard with password %s\n", dashboard.Keys[0].RawKey)
```
3) In /demo run `go run main.go`
4) On the terminal you will see the output with the password
> feat: support private dashboard creation

- checkly_test.go
- demo/main.go
- types.go
Following what was asked in this [thread](https://checklyhq.slack.com/archives/C024ZAJ938S/p1690276802718249) and this [issue](https://github.com/checkly/terraform-provider-checkly/issues/263), this PRs adds the `SSLCheckDomain` property into the `Check` type.
Note that `SSLCheckDomain` is ignored in wanted check output when running test. That's because, if the the property is empty, the value is generated in the backend. We can adjust test's `wantCheck` in a new PR.
> chore: add sslCheckDomain property [sc-0]

- types.go
This PR adds support for retry strategies to checks and check groups.
* double check is marked as deprecated, since it will be replaced by retry strategies
* We store a `*RetryStrategy` rather than a `RetryStrategy`. This makes it possible to have `nil` as the retry strategy. I haven't written much Go, so let me know if there's a more idiomatic way to do this. We already do the same for `BasicAuth` in `Request`.
> feat: add support for RetryStrategy

- types.go
Add new `alertSettings.parallelRunFailureThreshold` types
> feat: add new alertSettings.parallelRunFailureThreshold props [sc-00]

- checkly_test.go
- fixtures/CreateCheck.json
- fixtures/CreateGroup.json
- fixtures/GetCheck.json
- fixtures/UpdateCheck.json
- fixtures/UpdateGroup.json
- types.go
* Add the new IPFamily field to be used with the tf provider
> feat: add new ip family field to the types [sc-20606]

- checkly.go
- checkly_integration_test.go
- types.go
This PR adds support for TCP Checks. 
Not my proudest work but I stuck to the existing style. The whole SDK needs an overhaul.
A minimal integration test is included. It actually found an issue in the API (`checkType` is required for the PUT endpoint), but I added a reasonable workaround for it.
PR checks are failing because configured secrets point to some unknown Checkly account that does not have TCP checks enabled, apparently.
> feat: add support for TCP checks [sc-23026]

- checkly.go
- checkly_test.go
- types.go
When `omitempty` is specified for a property, the property is not sent to the server. Our `PUT` endpoints however act like `PATCH` would, meaning that partial updates are supported. When a property is not set, it is kept intact, even though the intention most likely was to remove it. Furthermore, using `null` value causes the same behavior as if the property was never given, so removing `omitempty` is not enough. Instead, we force empty `Locations` and `PrivateLocations` to always be sent as `[]` by initializing them as empty slices if not set.
The same issue likely exists for all other slices that have been marked `omitempty`. Whether they can also be changed or not requires some additional research. For now, only these two properties have been changed.
> fix: pass empty Locations and PrivateLocations to backend [sc-23129]

- checkly_test.go
- fixtures/CreateCheck.json
- fixtures/CreateGroup.json
- fixtures/GetCheck.json
- fixtures/UpdateCheck.json
- fixtures/UpdateGroup.json
DoubleCheck is now being converted to retryStrategy at the API level which broke tests. Use retryStrategy instead.
Some fixture files had incorrect indentation so there are a few unrelated lines that have changed. It's minor enough to keep in this PR.
> fix(tests): use retryStrategy in favor of deprecated doubleCheck [sc-23400]

- checkly.go
- checkly_integration_test.go
- checkly_test.go
- fixtures/CreateStatusPage.json
- fixtures/CreateStatusPageService.json
- fixtures/GetStatusPage.json
- fixtures/GetStatusPageService.json
- fixtures/UpdateStatusPage.json
- fixtures/UpdateStatusPageService.json
- types.go
Adds support for status pages and status page services.
Existing style has been respected, or in other words it's not pretty.
> feat: add status pages and status page services [sc-23757]

- checkly.go
- checkly_integration_test.go
- checkly_test.go
- fixtures/CreateURLMonitor.json
- fixtures/GetURLMonitor.json
- fixtures/UpdateURLMonitor.json
- types.go
This change also renames TCP and Heartbeat related functions and structs from Check to Monitor. Old names continue to work, but they have been marked deprecated.
Additionally, since we're going with the Monitor name, new dedicated Delete*Monitor functions have been introduced for URL, TCP and Heartbeat monitors. Behind the scenes they continue to call the universal DeleteCheck function.
> feat: add support for URL monitors [sc-24803]

- checkly_test.go
- fixtures/CreateDashboard.json
- types.go
Adds a new `EnableIncidents` flag to `Dashboard`, which will be used to resolve https://github.com/checkly/terraform-provider-checkly/issues/248.
> feat: add EnableIncidents to Dashboard [sc-25022]

- checkly_integration_test.go
- checkly_test.go
- fixtures/CreateDashboard.json
- types.go
This PR exposes the following new properties for Dashboards:
- ShowHeader
- ExpandChecks
- ShowCheckRunLinks
- CustomCSS
- ShowP95
- ShowP99
The properties have been added in a compatible manner, meaning that not specifying the values is going to have the same outcome as explicitly providing their default values. Unfortunately `ShowHeader`, `ShowP95` and `ShowP99` default to true, so they had to made inconvenient pointers.
This change also changes all `t.Error` to `t.Fatal` in the integration test file, because the former does not stop execution which led to a panic party when things went wrong.
> feat: expose more Dashboard properties [sc-25022]

- types.go
Technically the type was already supported (it's just a string), but we need to skip a few fields when talking with the backend to make the experience smoother.
> feat: add support for SINGLE_RETRY retry strategy [SIM-126]

- types.go
This PR adds support for a new `RetryStrategy` property, `OnlyOn`. The only supported value currently is `[]string{"NETWORK_ERROR"}` which makes the retry strategy only apply on network errors.
> feat: add support for the RetryStrategy OnlyOn property (limit to network failures) [SIM-127]
