checkly/checkly-go-sdk

types.go
fixes updates tags issue on tf provider
=> removing unnecessary omitempty for tags

checkly.go, checkly_test.go, types.go
=> fixing default filter values

checkly.go, types.go
* Added flag settings to AlertChannel
=> fixing alert channel flags

checkly.go
=> fixing sslExpirythreshold

Makefile, README.md, checkly.go, checkly_integration_test.go, checkly_test.go, types.go
* added client interface
* added context to all methods
=> added client interface + context

.gitignore, types.go, types_test.go
Add new type `AlertChannelPagerduty` and support for PagerDuty Integrations
=> feat: add support for pager duty alert channel

.github/auto_assign.yml, README.md
Resolves #38
Add auto_assign action with assigned reviewers
=> Add auto_assign action for PR's

README.md, checkly.go, examples/demo/main.go, types.go
Add support for setting Account ID (only for User API Keys)
> Resolves https://github.com/checkly/checkly-go-sdk/issues/51
=> feat: add support for account id

checkly.go, checkly_integration_test.go, checkly_test.go, examples/demo/main.go, testdata/CreateTriggerCheck.json, testdata/CreateTriggerGroup.json, types.go
Resolves #58 
- Added configuration support for check and group Triggers
=> Add support for command line triggers

checkly.go, checkly_test.go, testdata/CreateDashboard.json, testdata/CreateTriggerCheck.json, testdata/CreateTriggerGroup.json, types.go
- Add run `URL` to check and group triggers
=> feat: add url to triggers

checkly.go, types.go
Added the new `x-checkly-source` header to the API calls for tracking in Segment / downstream data sources. 
For API additions, see: https://github.com/checkly/checkly-backend/pull/2511
Terraform addition: https://github.com/checkly/terraform-provider-checkly/pull/109
=> feat: add x-checkly-source header [sc-00]

types.go
Add missing type definition for `AddChecklySource` method.
=> fix(types): add SetChecklySource type

types.go
Set `omitempty` in RepeatInterval property from `MaintenanceWindow` type
> Resolves #78
=> refactor: set `omitempty` in RepeatInterval property

.github/workflows/test.yml, checkly_integration_test.go
Use new user keys (with account id) in the integration tests
> Resolves #77
=> test: use user keys for integration tests

CHANGELOG.md, checkly.go, checkly_integration_test.go, checkly_test.go, demo/go.sum, demo/main.go, fixtures/CreatePrivateLocation.json, types.go
Resolves #86
- Add a new PrivateLocation type
- Add CRUD methods 
- Allow private location assignments in check/groups
- New tests
- Private Location examples
=> feat: add private locations support

checkly_test.go, fixtures/CreateDashboard.json, types.go
Add new Dashboard properties:
- favicon
- link
- description
- checksPerPage
- useTagsAndOperator
> Resolves #99
=> feat: add new dashboard properties

.github/workflows/release.yml, .github/workflows/test.yml, CONTRIBUTING.md, Makefile, go.mod, types.go
Hi, I read the contribution notes and found a few inconsistent things that I fixed. For example, [CONTRIBUTING.md](CONTRIBUTING.md) mentions `make fmt` that missing and there were a few typos. You mentioned the minimum go version as 1.18.x and tests using 1.15 that I fixed too.
=> Fix small things

checkly_test.go, types.go
Add keys to avoid failing integration tests
=> Add keys to avoid failing integration tests

CONTRIBUTING.md
=> Remove goreleaser from CONTRIBUTING.md

types.go, types_test.go
Add new types for `call` alert channel
=> feat: add phone call as alert channel types [sc-00]

.github/CODEOWNERS
=> feat: add code owners [sc-00]

.gitignore, checkly.go, demo/main.go, types.go
=> feature: support Heartbeat checks [sc-16785]

.github/CODEOWNERS
=> chore: fix code owners [sc-00]

types.go
We recently added support for retry strategies in the previous release (https://github.com/checkly/checkly-go-sdk/pull/113). This PR renames one of the retry strategy properties to a more accurate name.
=> feat: rename retry-strategy MaxAttempts to MaxRetries

types.go
Adding new `Secret` boolean to environment variables
> [!IMPORTANT]
> Important note: this feature is not available yet, if you have any questions feel free to reach out to our customer support
=> feat: add Secret type [sc-21027]
